version: '4'
services:
  mysql:
    image: mysql:9.0.0
    container_name: mysql
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql