version: '4'
services:
  mysql:
    image: mysql:9.0.0
    container_name: mysql2
    ports:
      - "3308:3308"
    environment:
      MYSQL_ROOT_PASSWORD: mysql2
    volumes:
      - ./docker/mysql/data:/var/lib/mysql